// AmberLit: Science Scope and Sequence
// Aligned to Australian Curriculum v9.0 Science.
// Foundation → Year 1 → Year 2

import type { ScienceUnit } from '@/types/curriculum';

export const SCIENCE_SEQUENCE: ScienceUnit[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // FOUNDATION (10 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: 'F.science.living_nonliving', yearLevel: 'F', strand: 'biological', title: 'Living and non-living things',
    term: 1, content: 'Distinguish between living and non-living things by observing features of growth, movement and response.',
    inquiryPrompts: ['What makes something alive?', 'Do all living things move?', 'Do all living things grow?'],
    sortingItems: ['dog', 'rock', 'tree', 'car', 'flower', 'water', 'bird', 'chair', 'worm', 'ball'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Look around the playground. What living things can you see?',
      'What non-living things can you find?',
      'How do you know something is alive?',
      'Can you find something that was once alive but is not now?',
      'Sort these pictures into living and non-living groups.',
      'What do all living things need?',
      'Is a rock living or non-living? Why?',
      'Is a tree living or non-living? Why?',
    ],
    investigationQuestions: ['What makes something alive?', 'Do all living things move?', 'Do all living things grow?'],
    investigationSteps: ['Look at objects around you', 'Decide if each one is living or non-living', 'Sort them into two groups', 'Draw your groups'],
    recordingPrompts: ['Draw a living thing you found', 'Draw a non-living thing you found', 'Write one thing living things do'],
    vocabulary: ['living', 'non-living', 'grow', 'move', 'eat', 'breathe', 'alive', 'dead'],
  },

  { id: 'F.science.needs', yearLevel: 'F', strand: 'biological', title: 'What living things need',
    term: 1, content: 'Identify the basic needs of living things: food, water, air, shelter.',
    inquiryPrompts: ['What do plants need?', 'What do animals need?', 'What happens without water?'],
    sortingItems: ['food', 'water', 'shelter', 'air', 'toys', 'television', 'sunlight', 'soil'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What does a pet need to stay healthy?',
      'Where do animals get their water?',
      'What do birds eat?',
      'Where do animals sleep?',
      'What happens if a plant does not get enough water?',
      'How do animals stay warm?',
      'How do animals stay cool?',
      'What do baby animals need from their parents?',
    ],
    investigationQuestions: ['What do all animals need?', 'Do different animals eat different things?', 'How do animals find shelter?'],
    investigationSteps: ['Think about what a pet needs', 'List food, water, shelter, and air', 'Compare with a wild animal', 'Draw what both need'],
    recordingPrompts: ['Draw what an animal needs', 'Write three things animals need', 'How do you help animals?'],
    vocabulary: ['food', 'water', 'shelter', 'air', 'healthy', 'survive', 'care', 'habitat'],
  },

  { id: 'F.science.body_parts', yearLevel: 'F', strand: 'biological', title: 'Parts of a plant',
    term: 1, content: 'Identify and label the parts of a plant: roots, stem, leaves, flower, seed.',
    inquiryPrompts: ['What parts does a plant have?', 'Why do plants need roots?', 'What do leaves do?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Look at this plant. Can you find the roots?',
      'Where are the leaves? How many can you count?',
      'Does this plant have flowers? What colour are they?',
      'Feel the stem. Is it hard or soft?',
      'What shape are the leaves?',
      'Can you find seeds on any plants?',
      'Compare two different plants. How are they the same?',
      'Compare two different plants. How are they different?',
    ],
    investigationQuestions: ['What parts does a plant have?', 'Why do plants need roots?', 'What do leaves do?'],
    investigationSteps: ['Look carefully at a plant', 'Find the roots, stem, leaves, and flowers', 'Draw each part', 'Label your drawing'],
    recordingPrompts: ['Draw a plant and label its parts', 'Which part is the tallest?', 'What colour are the leaves?'],
    vocabulary: ['root', 'stem', 'leaf', 'flower', 'seed', 'petal', 'soil', 'plant'],
  },

  { id: 'F.science.senses', yearLevel: 'F', strand: 'biological', title: 'Our five senses',
    term: 2, content: 'Explore the five senses and how we use them to observe the world.',
    inquiryPrompts: ['How do we use our senses?', 'Which sense helps us most?', 'What happens if we lose one sense?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Close your eyes. What can you hear?',
      'What does this object feel like? Smooth or rough?',
      'What can you smell in the kitchen?',
      'How does this taste? Sweet, sour, salty, or bitter?',
      'What colours can you see outside?',
      'Which senses do you use when eating?',
      'How do blind people read?',
      'What sense do you use to know it is raining?',
    ],
    investigationQuestions: ['How do we use our senses?', 'Which sense helps us most?', 'Can we identify objects without seeing them?'],
    investigationSteps: ['Put objects in a bag', 'Feel them without looking', 'Guess what each object is', 'Check by looking'],
    recordingPrompts: ['Draw something you can see, hear, smell, taste, and touch', 'Which sense helped you most today?', 'Write about your favourite smell'],
    vocabulary: ['sight', 'hearing', 'smell', 'taste', 'touch', 'senses', 'observe', 'describe'],
  },

  { id: 'F.science.materials', yearLevel: 'F', strand: 'chemical', title: 'Everyday materials',
    term: 2, content: 'Observe and describe properties of familiar materials used in everyday objects.',
    inquiryPrompts: ['What is this made of?', 'Why was this material chosen?', 'What else could it be made of?'],
    sortingItems: ['wood', 'plastic', 'metal', 'fabric', 'paper', 'glass', 'rubber', 'stone'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Feel this object. Is it smooth or rough?',
      'Is this material hard or soft?',
      'Can you bend this? Is it flexible or rigid?',
      'Is this object heavy or light?',
      'What colour is this material?',
      'Can you see through it? Is it transparent or opaque?',
      'Does it feel warm or cold?',
      'What happens when you squeeze it?',
    ],
    investigationQuestions: ['What words describe how things feel?', 'Are all hard things heavy?', 'Can soft things be strong?'],
    investigationSteps: ['Collect different objects', 'Feel and describe each one', 'Sort by smooth/rough, hard/soft', 'Record your sorting'],
    recordingPrompts: ['Draw an object and describe how it feels', 'Sort objects into hard and soft groups', 'Which material is your favourite? Why?'],
    vocabulary: ['smooth', 'rough', 'hard', 'soft', 'heavy', 'light', 'flexible', 'rigid', 'transparent', 'opaque'],
  },

  { id: 'F.science.properties', yearLevel: 'F', strand: 'chemical', title: 'Properties of materials',
    term: 2, content: 'Sort and classify objects based on observable properties like texture, colour, and flexibility.',
    inquiryPrompts: ['How can we sort materials?', 'Which materials float?', 'Which materials are waterproof?'],
    sortingItems: ['cotton', 'tin', 'cork', 'wool', 'clay', 'silk', 'sponge', 'foil', 'cardboard', 'leather'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Which objects float in water?', 'Which objects sink?', 'Can you sort objects by colour?',
      'Can you sort objects by texture?', 'Which materials bend easily?', 'Which materials break easily?',
      'Which materials are waterproof?', 'Which materials absorb water?',
    ],
    investigationQuestions: ['Which materials float and which sink?', 'How can we sort materials?', 'What makes a material waterproof?'],
    investigationSteps: ['Collect 10 different objects', 'Predict if each will float or sink', 'Test in a tub of water', 'Record your results'],
    recordingPrompts: ['Draw objects that float', 'Draw objects that sink', 'Were your predictions correct?'],
    vocabulary: ['float', 'sink', 'waterproof', 'absorbent', 'texture', 'property', 'sort', 'classify'],
  },

  { id: 'F.science.weather', yearLevel: 'F', strand: 'earth_space', title: 'Weather',
    term: 3, content: 'Observe and describe daily weather conditions and how they affect our activities.',
    inquiryPrompts: ['How does weather change?', 'What clothes do we wear in different weather?', 'How can we record weather?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What is the weather like today?', 'Is it sunny, cloudy, rainy, or windy?',
      'How does the weather make you feel?', 'What clothes do you wear when it is cold?',
      'What clothes do you wear when it is hot?', 'What season is it now?',
      'What happens to trees in autumn?', 'How is summer different from winter?',
    ],
    investigationQuestions: ['How does weather change?', 'What are the four seasons?', 'How does weather affect what we do?'],
    investigationSteps: ['Look outside and describe the weather', 'Record the weather for a week', 'Compare each day', 'Look for patterns'],
    recordingPrompts: ['Draw today\'s weather', 'Write if it is hot, warm, cool, or cold', 'What season is your favourite? Why?'],
    vocabulary: ['sunny', 'cloudy', 'rainy', 'windy', 'hot', 'cold', 'warm', 'cool', 'season', 'summer', 'autumn', 'winter', 'spring'],
  },

  { id: 'F.science.seasons', yearLevel: 'F', strand: 'earth_space', title: 'Seasons',
    term: 3, content: 'Recognise the four seasons and how living things respond to seasonal changes.',
    inquiryPrompts: ['What changes in each season?', 'How do animals prepare for winter?', 'What grows in spring?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What season is it now? How do you know?', 'What do trees look like in each season?',
      'What animals do you see in different seasons?', 'What foods grow in each season?',
      'How long are the days in summer vs winter?', 'What activities do you do in each season?',
      'How do farmers use seasons?', 'What season comes after autumn?',
    ],
    investigationQuestions: ['What changes between seasons?', 'How do plants change in each season?', 'Do all places have four seasons?'],
    investigationSteps: ['Draw a tree in each season', 'Label what is different', 'Write about your favourite season', 'Compare with a partner'],
    recordingPrompts: ['Draw one thing about each season', 'Which season has the longest days?', 'What do animals do in winter?'],
    vocabulary: ['season', 'spring', 'summer', 'autumn', 'winter', 'hibernate', 'migrate', 'deciduous', 'evergreen'],
  },

  { id: 'F.science.push_pull', yearLevel: 'F', strand: 'physical', title: 'Pushes and pulls',
    term: 4, content: 'Explore how pushes and pulls make objects move, stop, or change direction.',
    inquiryPrompts: ['What is a push?', 'What is a pull?', 'How can you make things move?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Push a toy car. What happens?', 'Pull a wagon. What happens?',
      'What happens when you push something heavy?', 'What happens when you push something light?',
      'Can you make a ball go faster?', 'Can you make a ball stop?',
      'What happens when two people push from opposite sides?', 'How do you open a door? Push or pull?',
    ],
    investigationQuestions: ['What is a push? What is a pull?', 'How can you make things move?', 'How can you make things stop?'],
    investigationSteps: ['Find objects you can push', 'Find objects you can pull', 'Try pushing with different strengths', 'Record what happens'],
    recordingPrompts: ['Draw something you pushed', 'Draw something you pulled', 'Write what happened when you pushed hard vs. softly'],
    vocabulary: ['push', 'pull', 'move', 'stop', 'fast', 'slow', 'force', 'direction', 'roll', 'slide'],
  },

  { id: 'F.science.movement', yearLevel: 'F', strand: 'physical', title: 'How things move',
    term: 4, content: 'Observe that objects move in different ways: rolling, sliding, bouncing, spinning.',
    inquiryPrompts: ['How many ways can things move?', 'Does shape affect how things move?', 'Does the surface matter?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'How does a ball move?', 'How does a swing move?', 'Can you make something spin?',
      'What moves in a straight line?', 'What moves in a zigzag?', 'What slides down a ramp?',
      'Do round things roll better than flat things?', 'What happens on a slippery surface vs. a rough one?',
    ],
    investigationQuestions: ['How many ways can things move?', 'Does shape affect how things move?', 'Does the surface matter?'],
    investigationSteps: ['Roll a ball on carpet', 'Roll it on tiles', 'Roll it on grass', 'Compare how far it goes each time'],
    recordingPrompts: ['Draw three ways things move', 'Which surface made the ball go furthest?', 'Why do you think that happened?'],
    vocabulary: ['roll', 'slide', 'bounce', 'spin', 'straight', 'curve', 'zigzag', 'surface', 'ramp', 'friction'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // YEAR 1 (9 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: '1.science.animal_features', yearLevel: '1', strand: 'biological', title: 'Animal features',
    term: 1, content: 'Identify external features of animals and how they help them survive.',
    inquiryPrompts: ['How are animals different from each other?', 'How do features help animals survive?', 'What coverings do animals have?'],
    sortingItems: ['fur', 'feathers', 'scales', 'legs_2', 'legs_4', 'legs_6', 'no_legs', 'wings', 'fins', 'claws'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What animals can you see outside?', 'Does this animal have legs? How many?',
      'Does it have fur, feathers, or scales?', 'How does this animal move?',
      'What sound does this animal make?', 'Where does this animal live?',
      'What do you think this animal eats?', 'How is a bird different from a dog?',
    ],
    investigationQuestions: ['How are animals different from each other?', 'How do animals move?', 'What coverings do animals have?'],
    investigationSteps: ['Choose two animals to compare', 'Look at how they move', 'Look at their coverings', 'Draw and compare them'],
    recordingPrompts: ['Draw your favourite animal', 'Write how it moves', 'Write what covers its body'],
    vocabulary: ['fur', 'feathers', 'scales', 'legs', 'wings', 'tail', 'beak', 'paws', 'claws', 'fins'],
  },

  { id: '1.science.habitats', yearLevel: '1', strand: 'biological', title: 'Animal habitats',
    term: 1, content: 'Explore where different animals live and why they live there.',
    inquiryPrompts: ['Why do different animals live in different places?', 'What does a habitat provide?', 'Can animals live anywhere?'],
    sortingItems: ['ocean', 'desert', 'forest', 'pond', 'arctic', 'grassland', 'rainforest', 'cave'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Where do birds live?', 'Where do fish live?', 'What animals live underground?',
      'Why do animals need a home?', 'What makes a good habitat?', 'How is a pond different from a desert?',
      'What animals live near your school?', 'What do animals find in their habitat?',
    ],
    investigationQuestions: ['Why do different animals live in different places?', 'What does a habitat provide?', 'Can animals live anywhere?'],
    investigationSteps: ['Choose an animal', 'Research where it lives', 'Draw its habitat', 'Label what the habitat provides'],
    recordingPrompts: ['Draw an animal in its habitat', 'List what the habitat provides', 'Compare two habitats'],
    vocabulary: ['habitat', 'shelter', 'food source', 'pond', 'forest', 'desert', 'ocean', 'burrow', 'nest', 'den'],
  },

  { id: '1.science.plant_parts', yearLevel: '1', strand: 'biological', title: 'Plant parts and growth',
    term: 2, content: 'Investigate what plants need to grow and observe growth over time.',
    inquiryPrompts: ['What do plants need to grow?', 'Do all seeds grow at the same rate?', 'What happens without sunlight?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What does a seed need to grow?', 'How long does it take a seed to sprout?',
      'What happens first when a seed grows?', 'Do all plants grow the same speed?',
      'What happens to a plant without light?', 'What happens to a plant without water?',
      'How tall is your plant today?', 'How many leaves does it have now?',
    ],
    investigationQuestions: ['What do plants need to grow?', 'Do all seeds grow at the same rate?', 'What happens without sunlight?'],
    investigationSteps: ['Plant two seeds', 'Put one in light, one in dark', 'Water both the same', 'Measure and compare over two weeks'],
    recordingPrompts: ['Draw your plant each week', 'Measure the height', 'Record how many leaves'],
    vocabulary: ['seed', 'sprout', 'germinate', 'sunlight', 'water', 'soil', 'growth', 'measure', 'roots', 'shoot'],
  },

  { id: '1.science.change', yearLevel: '1', strand: 'chemical', title: 'Solids, liquids, and gases',
    term: 2, content: 'Explore the three states of matter and how materials change.',
    inquiryPrompts: ['How are solids different from liquids?', 'Where is air?', 'Can things change from solid to liquid?'],
    sortingItems: ['ice', 'water', 'steam', 'rock', 'juice', 'air', 'milk', 'sand', 'honey', 'smoke'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Can you pour a rock?', 'Can you pour water?', 'Can you hold air in your hands?',
      'What shape is water in a cup vs. a bowl?', 'Does a solid keep its shape?',
      'Can you see air?', 'What happens to steam from a kettle?', 'Is toothpaste a solid or a liquid?',
    ],
    investigationQuestions: ['How are solids different from liquids?', 'Where is air?', 'Can things change from solid to liquid?'],
    investigationSteps: ['Collect solid objects', 'Pour water into different containers', 'Blow air into a balloon', 'Compare how each behaves'],
    recordingPrompts: ['Draw a solid, a liquid, and a gas', 'Write one property of each', 'Sort objects into solid/liquid/gas'],
    vocabulary: ['solid', 'liquid', 'gas', 'shape', 'pour', 'flow', 'air', 'steam', 'container', 'state'],
  },

  { id: '1.science.mixing', yearLevel: '1', strand: 'chemical', title: 'Mixing and changing',
    term: 3, content: 'Investigate what happens when materials are mixed together.',
    inquiryPrompts: ['What happens when we mix things?', 'Can all changes be undone?', 'What changes can heat make?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What happens when you mix sand and water?', 'Can you separate them again?',
      'What happens when you mix paint colours?', 'What happens to ice when it warms up?',
      'What happens to water when it gets very cold?', 'Can you change playdough back to flour and water?',
      'What happens when you stir sugar into water?', 'What changes can you see?',
    ],
    investigationQuestions: ['What happens when we mix things?', 'Can all changes be undone?', 'What changes can heat make?'],
    investigationSteps: ['Choose two things to mix', 'Predict what will happen', 'Mix them and observe', 'Record what you see'],
    recordingPrompts: ['Draw before and after mixing', 'Write what changed', 'Could you undo the change?'],
    vocabulary: ['mix', 'change', 'melt', 'freeze', 'dissolve', 'separate', 'combine', 'observe', 'reversible', 'irreversible'],
  },

  { id: '1.science.sky', yearLevel: '1', strand: 'earth_space', title: 'The sky and beyond',
    term: 3, content: 'Observe changes in the sky including day and night, the sun, moon and stars.',
    inquiryPrompts: ['Why do we have day and night?', 'How do shadows change?', 'What is in the night sky?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What can you see in the sky during the day?', 'What can you see in the sky at night?',
      'Where does the sun rise?', 'Where does the sun set?', 'What makes shadows?',
      'When are shadows long? When are they short?', 'Can you see the moon during the day sometimes?',
      'Why is it dark at night?',
    ],
    investigationQuestions: ['Why do we have day and night?', 'How do shadows change?', 'What is in the night sky?'],
    investigationSteps: ['Go outside and find your shadow', 'Trace your shadow in the morning', 'Trace it again at lunchtime', 'Compare the two shadows'],
    recordingPrompts: ['Draw the sky during the day', 'Draw the sky at night', 'Draw your shadow at two different times'],
    vocabulary: ['sun', 'moon', 'stars', 'shadow', 'sunrise', 'sunset', 'day', 'night', 'sky', 'bright', 'dark'],
  },

  { id: '1.science.resources', yearLevel: '1', strand: 'earth_space', title: 'Earth resources',
    term: 3, content: 'Explore natural and human-made resources and how we use them.',
    inquiryPrompts: ['What comes from the Earth?', 'How do we use water?', 'What are natural resources?'],
    sortingItems: ['water', 'wood', 'plastic', 'stone', 'cotton', 'metal', 'rubber', 'glass'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What is this made from?', 'Does it come from nature or a factory?',
      'How do we use water every day?', 'Where does wood come from?',
      'What happens if we waste resources?', 'How can we reuse things?',
      'What natural materials can you find outside?', 'Why should we save water?',
    ],
    investigationQuestions: ['What comes from the Earth?', 'How do we use water?', 'What can be recycled?'],
    investigationSteps: ['Collect objects from the classroom', 'Sort into natural and human-made', 'Discuss where each comes from', 'Draw your sorting'],
    recordingPrompts: ['List 5 natural resources', 'List 5 human-made materials', 'How can you save water?'],
    vocabulary: ['resource', 'natural', 'human-made', 'recycle', 'reuse', 'reduce', 'conserve', 'environment'],
  },

  { id: '1.science.light_sound', yearLevel: '1', strand: 'physical', title: 'Light and sound',
    term: 4, content: 'Investigate how light and sound are produced and how they travel.',
    inquiryPrompts: ['What makes light?', 'What makes sound?', 'Can sound travel through different materials?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What makes light?', 'What happens when you block the light?', 'Can you make a shadow bigger?',
      'What sounds can you hear right now?', 'Clap your hands. What makes the sound?',
      'Can you make a loud sound?', 'Can you make a quiet sound?', 'What happens when you pluck a rubber band?',
    ],
    investigationQuestions: ['What makes shadows?', 'Can you change a shadow?', 'What makes sound?'],
    investigationSteps: ['Shine a torch on different materials', 'Record which ones make shadows', 'Make sounds with different objects', 'Feel for vibrations'],
    recordingPrompts: ['Draw your shadow experiment', 'Which materials blocked light?', 'Draw something that makes a loud sound'],
    vocabulary: ['light', 'shadow', 'transparent', 'opaque', 'sound', 'loud', 'quiet', 'vibration', 'pitch', 'source'],
  },

  { id: '1.science.motion', yearLevel: '1', strand: 'physical', title: 'Forces and motion',
    term: 4, content: 'Investigate how forces affect the motion of objects on different surfaces.',
    inquiryPrompts: ['What forces act on objects?', 'How does friction affect movement?', 'Does the surface matter?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What makes a ball roll downhill?', 'Why does it take more effort on carpet?',
      'How does a ramp help things move?', 'What happens with different ramp heights?',
      'Does a heavy ball roll further than a light one?', 'What slows things down?',
      'Does a ball roll better on smooth or rough surfaces?', 'What happens when you change the ramp angle?',
    ],
    investigationQuestions: ['Does the surface affect how far a ball rolls?', 'Does ramp height matter?', 'Do heavier objects roll further?'],
    investigationSteps: ['Set up a ramp at different heights', 'Roll a car down each height', 'Measure how far it travels', 'Record and compare'],
    recordingPrompts: ['Draw your ramp experiment', 'Record the distances', 'Which height made the car go furthest?'],
    vocabulary: ['force', 'friction', 'ramp', 'surface', 'distance', 'speed', 'gravity', 'slope', 'smooth', 'rough'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // YEAR 2 (9 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: '2.science.life_cycles', yearLevel: '2', strand: 'biological', title: 'Life cycles',
    term: 1, content: 'Compare life cycles of different animals including metamorphosis.',
    inquiryPrompts: ['Do all animals start as babies?', 'How do animals change as they grow?', 'What animals come from eggs?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What does a baby chicken look like?', 'How does a caterpillar change?',
      'Do all babies look like their parents?', 'What is a tadpole?',
      'How does a frog grow?', 'What comes from an egg?',
      'How are puppies different from adult dogs?', 'What stages does a butterfly go through?',
    ],
    investigationQuestions: ['Do all animals start as babies?', 'How do animals change as they grow?', 'What animals come from eggs?'],
    investigationSteps: ['Choose an animal with an interesting life cycle', 'Draw each stage', 'Label the stages in order', 'Present to a partner'],
    recordingPrompts: ['Draw the life cycle stages', 'Write what happens at each stage', 'How long does each stage take?'],
    vocabulary: ['life cycle', 'egg', 'larva', 'pupa', 'adult', 'tadpole', 'caterpillar', 'chrysalis', 'hatch', 'metamorphosis'],
  },

  { id: '2.science.growth', yearLevel: '2', strand: 'biological', title: 'Growth and change',
    term: 1, content: 'Investigate how living things grow and change over time.',
    inquiryPrompts: ['How do plants grow?', 'What affects growth rate?', 'Do all living things grow the same way?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'How have you changed since you were a baby?', 'What do seeds need to germinate?',
      'Do plants grow faster with fertiliser?', 'How does temperature affect growth?',
      'What happens to a plant in too much sun?', 'How do we measure growth?',
      'What do young animals need from their parents?', 'At what age do humans stop growing?',
    ],
    investigationQuestions: ['What affects how fast plants grow?', 'Do all seeds germinate at the same rate?', 'Does temperature affect growth?'],
    investigationSteps: ['Plant seeds in two pots', 'Keep one warm and one cool', 'Measure growth daily for two weeks', 'Graph your results'],
    recordingPrompts: ['Record daily measurements', 'Graph the growth', 'Which conditions helped growth most?'],
    vocabulary: ['growth', 'germinate', 'seedling', 'mature', 'develop', 'conditions', 'temperature', 'measure', 'compare', 'record'],
  },

  { id: '2.science.food_chains', yearLevel: '2', strand: 'biological', title: 'Food chains',
    term: 2, content: 'Understand how energy moves through simple food chains.',
    inquiryPrompts: ['How does energy move through a food chain?', 'What are producers and consumers?', 'Why are food chains important?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What does a rabbit eat?', 'What eats a rabbit?', 'Where does the energy in food come from?',
      'What is a producer?', 'What is a consumer?', 'What happens if one animal in the chain disappears?',
      'Can you make a food chain for the ocean?', 'Are humans part of food chains?',
    ],
    investigationQuestions: ['How does energy move through a food chain?', 'What are producers and consumers?', 'Why are food chains important?'],
    investigationSteps: ['Draw a plant', 'Draw an animal that eats it', 'Draw an animal that eats that animal', 'Connect them with arrows'],
    recordingPrompts: ['Draw a food chain with 3-4 links', 'Label producers and consumers', 'What would happen if the producer disappeared?'],
    vocabulary: ['food chain', 'producer', 'consumer', 'predator', 'prey', 'energy', 'herbivore', 'carnivore', 'omnivore', 'decomposer'],
  },

  { id: '2.science.reversible', yearLevel: '2', strand: 'chemical', title: 'Reversible and irreversible changes',
    term: 2, content: 'Investigate changes that can and cannot be reversed through heating and cooling.',
    inquiryPrompts: ['How does heat change materials?', 'How does cold change materials?', 'Which changes are reversible?'],
    sortingItems: ['melting ice', 'baking cake', 'freezing water', 'burning wood', 'dissolving sugar', 'cooking egg', 'melting chocolate', 'toasting bread'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What happens to butter in a hot pan?', 'What happens to water in a freezer?',
      'Can you melt chocolate? How?', 'What happens to steam on a cold window?',
      'Is melting reversible?', 'What happens when you bake a cake?',
      'Can you un-bake a cake?', 'What is the difference between melting and dissolving?',
    ],
    investigationQuestions: ['How does heat change materials?', 'How does cold change materials?', 'Which changes are reversible?'],
    investigationSteps: ['Choose a material (ice, chocolate, butter)', 'Predict what heat will do', 'Apply heat and observe', 'Try cooling it back'],
    recordingPrompts: ['Draw before and after heating', 'Was the change reversible?', 'Write what you observed'],
    vocabulary: ['melt', 'freeze', 'boil', 'evaporate', 'condense', 'reversible', 'irreversible', 'heat', 'cool', 'temperature'],
  },

  { id: '2.science.properties_adv', yearLevel: '2', strand: 'chemical', title: 'Comparing material properties',
    term: 3, content: 'Compare properties of different materials and investigate which are best for specific purposes.',
    inquiryPrompts: ['Why are buildings made of brick?', 'What makes a good umbrella material?', 'Which material is strongest?'],
    sortingItems: ['strength', 'flexibility', 'waterproof', 'transparency', 'heat_resistance', 'weight'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Which material is strongest?', 'Which material bends the most?',
      'Which material keeps water out best?', 'Which material lets light through?',
      'Which material is lightest?', 'Which material is best for a raincoat?',
      'Why are windows made of glass?', 'Why are clothes made of fabric, not metal?',
    ],
    investigationQuestions: ['Which material is strongest?', 'Which material is most waterproof?', 'Why do we use different materials?'],
    investigationSteps: ['Test 5 materials for strength', 'Test for waterproofness', 'Test for flexibility', 'Rank and compare'],
    recordingPrompts: ['Record test results in a table', 'Which material was strongest?', 'Which material is best for an umbrella?'],
    vocabulary: ['property', 'strength', 'flexibility', 'waterproof', 'durability', 'transparent', 'opaque', 'test', 'compare', 'purpose'],
  },

  { id: '2.science.water_cycle', yearLevel: '2', strand: 'earth_space', title: 'The water cycle',
    term: 3, content: 'Investigate evaporation, condensation, and precipitation in the water cycle.',
    inquiryPrompts: ['Where does rain come from?', 'What is evaporation?', 'How does water move in a cycle?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Where does rain come from?', 'What happens to puddles on a sunny day?',
      'Where does the water go?', 'What are clouds made of?',
      'Why does it rain?', 'Where does river water come from?',
      'What happens to water on a hot footpath?', 'Can you see evaporation happening?',
    ],
    investigationQuestions: ['Where does rain come from?', 'What is evaporation?', 'How does water move in a cycle?'],
    investigationSteps: ['Put water in a container in the sun', 'Cover with cling wrap', 'Observe after a few hours', 'Record where water droplets appear'],
    recordingPrompts: ['Draw the water cycle', 'Label evaporation, condensation, and precipitation', 'Explain what you saw'],
    vocabulary: ['evaporation', 'condensation', 'precipitation', 'water cycle', 'cloud', 'rain', 'puddle', 'vapour', 'droplet', 'collect'],
  },

  { id: '2.science.erosion', yearLevel: '2', strand: 'earth_space', title: 'Erosion and Earth changes',
    term: 3, content: 'Investigate how wind, water, and ice change the Earth\'s surface over time.',
    inquiryPrompts: ['How does water shape the land?', 'What is erosion?', 'How do mountains form?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What happens when rain hits bare soil?', 'Where does the soil go?',
      'How do rivers change the land?', 'What do you notice about rocks near a river?',
      'How does wind move sand?', 'What do sand dunes look like?',
      'How are beaches formed?', 'What happens to rocks over millions of years?',
    ],
    investigationQuestions: ['How does water shape the land?', 'What is erosion?', 'Can we slow down erosion?'],
    investigationSteps: ['Build a small hill of sand', 'Pour water slowly over it', 'Observe what happens', 'Try adding grass or sticks to slow erosion'],
    recordingPrompts: ['Draw before and after the water', 'What happened to the hill?', 'Did anything slow the erosion?'],
    vocabulary: ['erosion', 'weathering', 'sediment', 'deposit', 'river', 'beach', 'cliff', 'sand', 'soil', 'landform'],
  },

  { id: '2.science.heat', yearLevel: '2', strand: 'physical', title: 'Heat energy',
    term: 4, content: 'Investigate how heat moves between objects and affects materials.',
    inquiryPrompts: ['How does heat move?', 'What materials conduct heat?', 'Why do we use oven mitts?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'Why does a metal spoon get hot in soup?', 'Why does an ice block melt in your hand?',
      'What materials keep things warm?', 'What materials keep things cold?',
      'Why do we wear jackets in winter?', 'Why are saucepans made of metal?',
      'Why are handles often made of plastic or wood?', 'What happens to chocolate in your pocket?',
    ],
    investigationQuestions: ['How does heat move?', 'What materials conduct heat best?', 'What materials insulate best?'],
    investigationSteps: ['Wrap ice in different materials', 'Predict which will melt first', 'Check every 10 minutes', 'Record which melted fastest and slowest'],
    recordingPrompts: ['Record melting times', 'Which material was the best insulator?', 'Which was the worst?'],
    vocabulary: ['heat', 'temperature', 'conduct', 'insulate', 'warm', 'cool', 'transfer', 'thermometer', 'energy', 'melt'],
  },

  { id: '2.science.electricity', yearLevel: '2', strand: 'physical', title: 'Simple electricity',
    term: 4, content: 'Explore simple circuits and how electricity powers everyday devices.',
    inquiryPrompts: ['What uses electricity?', 'How does a simple circuit work?', 'What is a conductor?'],
    activities: ['science_explore', 'science_investigate'],
    observationPrompts: [
      'What things in your house use electricity?', 'What happens when you flip a light switch?',
      'Where does electricity come from?', 'What is a battery?',
      'Can you make a light bulb work with a battery?', 'What happens if you break the circuit?',
      'What materials let electricity flow through?', 'Why are wires covered in plastic?',
    ],
    investigationQuestions: ['What uses electricity?', 'How does a simple circuit work?', 'What is a conductor vs an insulator?'],
    investigationSteps: ['Build a simple circuit with a battery, wire, and bulb', 'Test if the bulb lights up', 'Try adding different materials to the circuit', 'Record which ones complete the circuit'],
    recordingPrompts: ['Draw your circuit', 'Which materials conducted electricity?', 'Which materials did not?'],
    vocabulary: ['electricity', 'circuit', 'battery', 'wire', 'bulb', 'switch', 'conductor', 'insulator', 'current', 'energy'],
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getScienceForYear(yearLevel: 'F' | '1' | '2'): ScienceUnit[] {
  const prefix = yearLevel === 'F' ? 'F.' : `${yearLevel}.`;
  return SCIENCE_SEQUENCE.filter((u) => u.id.startsWith(prefix));
}
