// AmberLit: Science Scope and Sequence
// Aligned to Australian Curriculum v9.0 Science.
// Foundation → Year 1 → Year 2

export interface ScienceUnit {
  id: string;
  strand: 'biological' | 'chemical' | 'earth_space' | 'physical' | 'inquiry';
  title: string;
  acDescriptor: string;
  week: number;
  observationPrompts: string[];
  investigationQuestions: string[];
  investigationSteps: string[];
  recordingPrompts: string[];
  vocabulary: string[];
}

export const SCIENCE_SEQUENCE: ScienceUnit[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // FOUNDATION
  // ═══════════════════════════════════════════════════════════════════════════

  // Biological Sciences
  { id: 'F.science.bio.01', strand: 'biological', title: 'Living and non-living things',
    acDescriptor: 'AC9SFU01', week: 1,
    observationPrompts: [
      'Look around the playground. What living things can you see?',
      'What non-living things can you find?',
      'How do you know something is alive?',
      'Can you find something that was once alive but is not now?',
      'Sort these pictures into living and non-living groups.',
      'What do all living things need?',
      'Is a rock living or non-living? Why?',
      'Is a tree living or non-living? Why?',
    ],
    investigationQuestions: ['What makes something alive?', 'Do all living things move?', 'Do all living things grow?'],
    investigationSteps: ['Look at objects around you', 'Decide if each one is living or non-living', 'Sort them into two groups', 'Draw your groups'],
    recordingPrompts: ['Draw a living thing you found', 'Draw a non-living thing you found', 'Write one thing living things do'],
    vocabulary: ['living', 'non-living', 'grow', 'move', 'eat', 'breathe', 'alive', 'dead'],
  },
  { id: 'F.science.bio.02', strand: 'biological', title: 'Parts of a plant',
    acDescriptor: 'AC9SFU01', week: 4,
    observationPrompts: [
      'Look at this plant. Can you find the roots?',
      'Where are the leaves? How many can you count?',
      'Does this plant have flowers? What colour are they?',
      'Feel the stem. Is it hard or soft?',
      'What shape are the leaves?',
      'Can you find seeds on any plants?',
      'Compare two different plants. How are they the same?',
      'Compare two different plants. How are they different?',
    ],
    investigationQuestions: ['What parts does a plant have?', 'Why do plants need roots?', 'What do leaves do?'],
    investigationSteps: ['Look carefully at a plant', 'Find the roots, stem, leaves, and flowers', 'Draw each part', 'Label your drawing'],
    recordingPrompts: ['Draw a plant and label its parts', 'Which part is the tallest?', 'What colour are the leaves?'],
    vocabulary: ['root', 'stem', 'leaf', 'flower', 'seed', 'petal', 'soil', 'plant'],
  },
  { id: 'F.science.bio.03', strand: 'biological', title: 'Animals and their features',
    acDescriptor: 'AC9SFU01', week: 8,
    observationPrompts: [
      'What animals can you see outside?',
      'Does this animal have legs? How many?',
      'Does it have fur, feathers, or scales?',
      'How does this animal move?',
      'What sound does this animal make?',
      'Where does this animal live?',
      'What do you think this animal eats?',
      'How is a bird different from a dog?',
    ],
    investigationQuestions: ['How are animals different from each other?', 'How do animals move?', 'What coverings do animals have?'],
    investigationSteps: ['Choose two animals to compare', 'Look at how they move', 'Look at their coverings', 'Draw and compare them'],
    recordingPrompts: ['Draw your favourite animal', 'Write how it moves', 'Write what covers its body'],
    vocabulary: ['fur', 'feathers', 'scales', 'legs', 'wings', 'tail', 'beak', 'paws'],
  },
  { id: 'F.science.bio.04', strand: 'biological', title: 'What animals need',
    acDescriptor: 'AC9SFU01', week: 12,
    observationPrompts: [
      'What does a pet need to stay healthy?',
      'Where do animals get their water?',
      'What do birds eat?',
      'Where do animals sleep?',
      'What happens if an animal does not get enough water?',
      'How do animals stay warm?',
      'How do animals stay cool?',
      'What do baby animals need from their parents?',
    ],
    investigationQuestions: ['What do all animals need?', 'Do different animals eat different things?', 'How do animals find shelter?'],
    investigationSteps: ['Think about what a pet needs', 'List food, water, shelter, and air', 'Compare with a wild animal', 'Draw what both need'],
    recordingPrompts: ['Draw what an animal needs', 'Write three things animals need', 'How do you help animals?'],
    vocabulary: ['food', 'water', 'shelter', 'air', 'healthy', 'survive', 'care', 'habitat'],
  },

  // Chemical Sciences
  { id: 'F.science.chem.01', strand: 'chemical', title: 'Properties of materials',
    acDescriptor: 'AC9SFU02', week: 6,
    observationPrompts: [
      'Feel this object. Is it smooth or rough?',
      'Is this material hard or soft?',
      'Can you bend this? Is it flexible or rigid?',
      'Is this object heavy or light?',
      'What colour is this material?',
      'Can you see through it? Is it transparent or opaque?',
      'Does it feel warm or cold?',
      'What happens when you squeeze it?',
    ],
    investigationQuestions: ['What words describe how things feel?', 'Are all hard things heavy?', 'Can soft things be strong?'],
    investigationSteps: ['Collect different objects', 'Feel and describe each one', 'Sort by smooth/rough, hard/soft', 'Record your sorting'],
    recordingPrompts: ['Draw an object and describe how it feels', 'Sort objects into hard and soft groups', 'Which material is your favourite? Why?'],
    vocabulary: ['smooth', 'rough', 'hard', 'soft', 'heavy', 'light', 'flexible', 'rigid', 'transparent', 'opaque'],
  },
  { id: 'F.science.chem.02', strand: 'chemical', title: 'Mixing and changing',
    acDescriptor: 'AC9SFU02', week: 16,
    observationPrompts: [
      'What happens when you mix sand and water?',
      'Can you separate them again?',
      'What happens when you mix paint colours?',
      'What happens to ice when it warms up?',
      'What happens to water when it gets very cold?',
      'Can you change playdough back to flour and water?',
      'What happens when you stir sugar into water?',
      'What changes can you see?',
    ],
    investigationQuestions: ['What happens when we mix things?', 'Can all changes be undone?', 'What changes can heat make?'],
    investigationSteps: ['Choose two things to mix', 'Predict what will happen', 'Mix them and observe', 'Record what you see'],
    recordingPrompts: ['Draw before and after mixing', 'Write what changed', 'Could you undo the change?'],
    vocabulary: ['mix', 'change', 'melt', 'freeze', 'dissolve', 'separate', 'combine', 'observe'],
  },

  // Earth and Space Sciences
  { id: 'F.science.earth.01', strand: 'earth_space', title: 'Weather and seasons',
    acDescriptor: 'AC9SFU03', week: 10,
    observationPrompts: [
      'What is the weather like today?',
      'Is it sunny, cloudy, rainy, or windy?',
      'How does the weather make you feel?',
      'What clothes do you wear when it is cold?',
      'What clothes do you wear when it is hot?',
      'What season is it now?',
      'What happens to trees in autumn?',
      'How is summer different from winter?',
    ],
    investigationQuestions: ['How does weather change?', 'What are the four seasons?', 'How does weather affect what we do?'],
    investigationSteps: ['Look outside and describe the weather', 'Record the weather for a week', 'Compare each day', 'Look for patterns'],
    recordingPrompts: ['Draw today\'s weather', 'Write if it is hot, warm, cool, or cold', 'What season is your favourite? Why?'],
    vocabulary: ['sunny', 'cloudy', 'rainy', 'windy', 'hot', 'cold', 'warm', 'cool', 'season', 'summer', 'autumn', 'winter', 'spring'],
  },
  { id: 'F.science.earth.02', strand: 'earth_space', title: 'Day and night',
    acDescriptor: 'AC9SFU03', week: 20,
    observationPrompts: [
      'What can you see in the sky during the day?',
      'What can you see in the sky at night?',
      'Where does the sun rise?',
      'Where does the sun set?',
      'What makes shadows?',
      'When are shadows long? When are they short?',
      'Can you see the moon during the day sometimes?',
      'Why is it dark at night?',
    ],
    investigationQuestions: ['Why do we have day and night?', 'How do shadows change?', 'What is in the night sky?'],
    investigationSteps: ['Go outside and find your shadow', 'Trace your shadow in the morning', 'Trace it again at lunchtime', 'Compare the two shadows'],
    recordingPrompts: ['Draw the sky during the day', 'Draw the sky at night', 'Draw your shadow at two different times'],
    vocabulary: ['sun', 'moon', 'stars', 'shadow', 'sunrise', 'sunset', 'day', 'night', 'sky', 'bright', 'dark'],
  },

  // Physical Sciences
  { id: 'F.science.phys.01', strand: 'physical', title: 'Pushes and pulls',
    acDescriptor: 'AC9SFU04', week: 14,
    observationPrompts: [
      'Push a toy car. What happens?',
      'Pull a wagon. What happens?',
      'What happens when you push something heavy?',
      'What happens when you push something light?',
      'Can you make a ball go faster?',
      'Can you make a ball stop?',
      'What happens when two people push from opposite sides?',
      'How do you open a door? Push or pull?',
    ],
    investigationQuestions: ['What is a push? What is a pull?', 'How can you make things move?', 'How can you make things stop?'],
    investigationSteps: ['Find objects you can push', 'Find objects you can pull', 'Try pushing with different strengths', 'Record what happens'],
    recordingPrompts: ['Draw something you pushed', 'Draw something you pulled', 'Write what happened when you pushed hard vs. softly'],
    vocabulary: ['push', 'pull', 'move', 'stop', 'fast', 'slow', 'force', 'direction', 'roll', 'slide'],
  },
  { id: 'F.science.phys.02', strand: 'physical', title: 'How things move',
    acDescriptor: 'AC9SFU04', week: 22,
    observationPrompts: [
      'How does a ball move?',
      'How does a swing move?',
      'Can you make something spin?',
      'What moves in a straight line?',
      'What moves in a zigzag?',
      'What slides down a ramp?',
      'Do round things roll better than flat things?',
      'What happens on a slippery surface vs. a rough one?',
    ],
    investigationQuestions: ['How many ways can things move?', 'Does shape affect how things move?', 'Does the surface matter?'],
    investigationSteps: ['Roll a ball on carpet', 'Roll it on tiles', 'Roll it on grass', 'Compare how far it goes each time'],
    recordingPrompts: ['Draw three ways things move', 'Which surface made the ball go furthest?', 'Why do you think that happened?'],
    vocabulary: ['roll', 'slide', 'bounce', 'spin', 'straight', 'curve', 'zigzag', 'surface', 'ramp', 'friction'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // YEAR 1
  // ═══════════════════════════════════════════════════════════════════════════

  { id: '1.science.bio.01', strand: 'biological', title: 'Animal habitats',
    acDescriptor: 'AC9S1U01', week: 1,
    observationPrompts: [
      'Where do birds live?', 'Where do fish live?', 'What animals live underground?',
      'Why do animals need a home?', 'What makes a good habitat?', 'How is a pond different from a desert?',
      'What animals live near your school?', 'What do animals find in their habitat?',
    ],
    investigationQuestions: ['Why do different animals live in different places?', 'What does a habitat provide?', 'Can animals live anywhere?'],
    investigationSteps: ['Choose an animal', 'Research where it lives', 'Draw its habitat', 'Label what the habitat provides'],
    recordingPrompts: ['Draw an animal in its habitat', 'List what the habitat provides', 'Compare two habitats'],
    vocabulary: ['habitat', 'shelter', 'food source', 'pond', 'forest', 'desert', 'ocean', 'burrow', 'nest', 'den'],
  },
  { id: '1.science.bio.02', strand: 'biological', title: 'Plant growth',
    acDescriptor: 'AC9S1U01', week: 5,
    observationPrompts: [
      'What does a seed need to grow?', 'How long does it take a seed to sprout?',
      'What happens first when a seed grows?', 'Do all plants grow the same speed?',
      'What happens to a plant without light?', 'What happens to a plant without water?',
      'How tall is your plant today?', 'How many leaves does it have now?',
    ],
    investigationQuestions: ['What do plants need to grow?', 'Do all seeds grow at the same rate?', 'What happens without sunlight?'],
    investigationSteps: ['Plant two seeds', 'Put one in light, one in dark', 'Water both the same', 'Measure and compare over two weeks'],
    recordingPrompts: ['Draw your plant each week', 'Measure the height', 'Record how many leaves'],
    vocabulary: ['seed', 'sprout', 'germinate', 'sunlight', 'water', 'soil', 'growth', 'measure', 'roots', 'shoot'],
  },
  { id: '1.science.bio.03', strand: 'biological', title: 'Animal life cycles',
    acDescriptor: 'AC9S1U01', week: 9,
    observationPrompts: [
      'What does a baby chicken look like?', 'How does a caterpillar change?',
      'Do all babies look like their parents?', 'What is a tadpole?',
      'How does a frog grow?', 'What comes from an egg?',
      'How are puppies different from adult dogs?', 'What stages does a butterfly go through?',
    ],
    investigationQuestions: ['Do all animals start as babies?', 'How do animals change as they grow?', 'What animals come from eggs?'],
    investigationSteps: ['Choose an animal with an interesting life cycle', 'Draw each stage', 'Label the stages in order', 'Present to a partner'],
    recordingPrompts: ['Draw the life cycle stages', 'Write what happens at each stage', 'How long does each stage take?'],
    vocabulary: ['life cycle', 'egg', 'larva', 'pupa', 'adult', 'tadpole', 'caterpillar', 'chrysalis', 'hatch', 'metamorphosis'],
  },
  { id: '1.science.chem.01', strand: 'chemical', title: 'Solids, liquids, and gases',
    acDescriptor: 'AC9S1U02', week: 7,
    observationPrompts: [
      'Can you pour a rock?', 'Can you pour water?', 'Can you hold air in your hands?',
      'What shape is water in a cup vs. a bowl?', 'Does a solid keep its shape?',
      'Can you see air?', 'What happens to steam from a kettle?', 'Is toothpaste a solid or a liquid?',
    ],
    investigationQuestions: ['How are solids different from liquids?', 'Where is air?', 'Can things change from solid to liquid?'],
    investigationSteps: ['Collect solid objects', 'Pour water into different containers', 'Blow air into a balloon', 'Compare how each behaves'],
    recordingPrompts: ['Draw a solid, a liquid, and a gas', 'Write one property of each', 'Sort objects into solid/liquid/gas'],
    vocabulary: ['solid', 'liquid', 'gas', 'shape', 'pour', 'flow', 'air', 'steam', 'container', 'state'],
  },
  { id: '1.science.earth.01', strand: 'earth_space', title: 'Rocks and soil',
    acDescriptor: 'AC9S1U03', week: 13,
    observationPrompts: [
      'What does this rock look like?', 'Is it smooth or rough?', 'What colour is the soil here?',
      'Are all rocks the same?', 'What is soil made of?', 'Can you find tiny rocks in soil?',
      'Where do rocks come from?', 'Why is some soil dark and some light?',
    ],
    investigationQuestions: ['How are rocks different?', 'What is soil made of?', 'Are there different types of soil?'],
    investigationSteps: ['Collect 5 different rocks', 'Describe each rock\'s properties', 'Look at soil through a magnifier', 'Draw what you see'],
    recordingPrompts: ['Draw and label your rocks', 'Describe the soil', 'Sort rocks by one property'],
    vocabulary: ['rock', 'soil', 'mineral', 'smooth', 'rough', 'colour', 'texture', 'magnifier', 'grain', 'sand', 'clay'],
  },
  { id: '1.science.phys.01', strand: 'physical', title: 'Light and shadows',
    acDescriptor: 'AC9S1U04', week: 17,
    observationPrompts: [
      'What makes light?', 'What happens when you block the light?', 'Can you make a shadow bigger?',
      'Can you make a shadow smaller?', 'What colour are shadows?', 'Do transparent things make shadows?',
      'Where is the shadow when the light is behind you?', 'What happens to shadows at different times of day?',
    ],
    investigationQuestions: ['What makes shadows?', 'Can you change a shadow?', 'Do all materials make shadows?'],
    investigationSteps: ['Shine a torch on different materials', 'Record which ones make shadows', 'Move the torch closer and further', 'Record how the shadow changes'],
    recordingPrompts: ['Draw your shadow experiment', 'Which materials blocked light?', 'How did distance change the shadow?'],
    vocabulary: ['light', 'shadow', 'transparent', 'opaque', 'translucent', 'torch', 'block', 'source', 'dark', 'bright'],
  },
  { id: '1.science.phys.02', strand: 'physical', title: 'Sound',
    acDescriptor: 'AC9S1U04', week: 21,
    observationPrompts: [
      'What sounds can you hear right now?', 'Clap your hands. What makes the sound?',
      'Can you make a loud sound?', 'Can you make a quiet sound?', 'What happens when you pluck a rubber band?',
      'Can sound travel through water?', 'What is vibration?', 'How do drums make sound?',
    ],
    investigationQuestions: ['What makes sound?', 'How can we change sounds?', 'Can sound travel through different materials?'],
    investigationSteps: ['Make sounds with different objects', 'Feel for vibrations', 'Try to make each sound louder and quieter', 'Record your findings'],
    recordingPrompts: ['Draw something that makes a loud sound', 'Draw something that makes a quiet sound', 'What vibrated?'],
    vocabulary: ['sound', 'loud', 'quiet', 'vibration', 'pitch', 'high', 'low', 'hear', 'ear', 'instrument'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // YEAR 2
  // ═══════════════════════════════════════════════════════════════════════════

  { id: '2.science.bio.01', strand: 'biological', title: 'Living things and their needs',
    acDescriptor: 'AC9S2U01', week: 1,
    observationPrompts: [
      'What do plants need that animals also need?', 'How do desert plants survive without much water?',
      'Why do some animals migrate?', 'How do penguins stay warm?',
      'What would happen if bees disappeared?', 'How do plants get energy?',
      'Why do fish have gills?', 'How do animals adapt to their environment?',
    ],
    investigationQuestions: ['How do living things survive in different environments?', 'What adaptations help animals?', 'How do plants adapt?'],
    investigationSteps: ['Choose an animal from a harsh environment', 'Research its adaptations', 'Draw the animal and label adaptations', 'Explain how each helps it survive'],
    recordingPrompts: ['Draw an adapted animal', 'Label its special features', 'Explain one adaptation'],
    vocabulary: ['adaptation', 'survive', 'environment', 'migrate', 'hibernate', 'camouflage', 'predator', 'prey', 'energy', 'nutrients'],
  },
  { id: '2.science.bio.02', strand: 'biological', title: 'Food chains',
    acDescriptor: 'AC9S2U01', week: 5,
    observationPrompts: [
      'What does a rabbit eat?', 'What eats a rabbit?', 'Where does the energy in food come from?',
      'What is a producer?', 'What is a consumer?', 'What happens if one animal in the chain disappears?',
      'Can you make a food chain for the ocean?', 'Are humans part of food chains?',
    ],
    investigationQuestions: ['How does energy move through a food chain?', 'What are producers and consumers?', 'Why are food chains important?'],
    investigationSteps: ['Draw a plant', 'Draw an animal that eats it', 'Draw an animal that eats that animal', 'Connect them with arrows'],
    recordingPrompts: ['Draw a food chain with 3-4 links', 'Label producers and consumers', 'What would happen if the producer disappeared?'],
    vocabulary: ['food chain', 'producer', 'consumer', 'predator', 'prey', 'energy', 'herbivore', 'carnivore', 'omnivore', 'decomposer'],
  },
  { id: '2.science.chem.01', strand: 'chemical', title: 'Heating and cooling changes',
    acDescriptor: 'AC9S2U02', week: 9,
    observationPrompts: [
      'What happens to butter in a hot pan?', 'What happens to water in a freezer?',
      'Can you melt chocolate? How?', 'What happens to steam on a cold window?',
      'Is melting reversible?', 'What happens when you bake a cake?',
      'Can you un-bake a cake?', 'What is the difference between melting and dissolving?',
    ],
    investigationQuestions: ['How does heat change materials?', 'How does cold change materials?', 'Which changes are reversible?'],
    investigationSteps: ['Choose a material (ice, chocolate, butter)', 'Predict what heat will do', 'Apply heat and observe', 'Try cooling it back'],
    recordingPrompts: ['Draw before and after heating', 'Was the change reversible?', 'Write what you observed'],
    vocabulary: ['melt', 'freeze', 'boil', 'evaporate', 'condense', 'reversible', 'irreversible', 'heat', 'cool', 'temperature'],
  },
  { id: '2.science.earth.01', strand: 'earth_space', title: 'Water cycle',
    acDescriptor: 'AC9S2U03', week: 13,
    observationPrompts: [
      'Where does rain come from?', 'What happens to puddles on a sunny day?',
      'Where does the water go?', 'What are clouds made of?',
      'Why does it rain?', 'Where does river water come from?',
      'What happens to water on a hot footpath?', 'Can you see evaporation happening?',
    ],
    investigationQuestions: ['Where does rain come from?', 'What is evaporation?', 'How does water move in a cycle?'],
    investigationSteps: ['Put water in a container in the sun', 'Cover with cling wrap', 'Observe after a few hours', 'Record where water droplets appear'],
    recordingPrompts: ['Draw the water cycle', 'Label evaporation, condensation, and precipitation', 'Explain what you saw'],
    vocabulary: ['evaporation', 'condensation', 'precipitation', 'water cycle', 'cloud', 'rain', 'puddle', 'vapour', 'droplet', 'collect'],
  },
  { id: '2.science.phys.01', strand: 'physical', title: 'Forces and motion',
    acDescriptor: 'AC9S2U04', week: 17,
    observationPrompts: [
      'What force makes a ball roll downhill?', 'Why do things fall when you drop them?',
      'What is friction?', 'Why is it harder to push on carpet than tiles?',
      'How do magnets push and pull?', 'Can magnets work through paper?',
      'What happens when two magnets come together?', 'How does a ramp change how far things travel?',
    ],
    investigationQuestions: ['What forces act on objects?', 'How does friction affect movement?', 'How do magnets work?'],
    investigationSteps: ['Set up a ramp at different heights', 'Roll a car down each height', 'Measure how far it travels', 'Record and compare'],
    recordingPrompts: ['Draw your ramp experiment', 'Record the distances', 'Which height made the car go furthest?'],
    vocabulary: ['force', 'gravity', 'friction', 'magnet', 'attract', 'repel', 'ramp', 'surface', 'distance', 'speed'],
  },
  { id: '2.science.phys.02', strand: 'physical', title: 'Simple machines',
    acDescriptor: 'AC9S2U04', week: 21,
    observationPrompts: [
      'How does a seesaw work?', 'What is a lever?', 'How does a ramp help us?',
      'Why is it easier to push something up a ramp than lift it?', 'What is a wheel and axle?',
      'Can you find simple machines in the classroom?', 'How does a pulley help?',
      'What simple machines are on the playground?',
    ],
    investigationQuestions: ['How do simple machines help us?', 'What is a lever?', 'How does a ramp make work easier?'],
    investigationSteps: ['Try lifting a heavy book', 'Now use a lever (ruler on a pencil) to lift it', 'Compare the effort', 'Record which was easier'],
    recordingPrompts: ['Draw a simple machine you found', 'Explain how it helps', 'Design your own simple machine'],
    vocabulary: ['lever', 'ramp', 'inclined plane', 'wheel', 'axle', 'pulley', 'effort', 'load', 'simple machine', 'fulcrum'],
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getScienceForYear(yearLevel: 'F' | '1' | '2'): ScienceUnit[] {
  const prefix = yearLevel === 'F' ? 'F.' : `${yearLevel}.`;
  return SCIENCE_SEQUENCE.filter((u) => u.id.startsWith(prefix));
}
