// AmberLit: Digital Technologies Scope and Sequence
// Aligned to Australian Curriculum v9.0 Digital Technologies.
// Foundation → Year 1 → Year 2

import type { DigitalUnit, DigitalVariant } from '@/types/curriculum';

export const DIGITAL_SEQUENCE: DigitalUnit[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // FOUNDATION (7 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: 'F.digital.devices', yearLevel: 'F', strand: 'digital_systems', title: 'Digital devices around us',
    term: 1, content: 'Identify common digital devices and describe what they do.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'Look around the room for digital devices',
      'Name each device you find',
      'What does each device do?',
      'Does it have a screen?',
      'Does it have buttons?',
      'How do you turn it on?',
      'Draw three digital devices',
      'Write what each one is used for',
    ],
    vocabulary: ['device', 'screen', 'keyboard', 'tablet', 'computer', 'phone', 'digital', 'technology'],
  },

  { id: 'F.digital.parts', yearLevel: 'F', strand: 'digital_systems', title: 'Parts of a computer',
    term: 1, content: 'Identify the main parts of a computer: screen, keyboard, mouse, speaker.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'Find the screen on this computer',
      'Find the keyboard — what is it for?',
      'Find the mouse — how do you use it?',
      'Where are the speakers?',
      'What other parts can you see?',
      'Draw a computer and label its parts',
      'What part do you type on?',
      'What part do you look at?',
    ],
    vocabulary: ['screen', 'monitor', 'keyboard', 'mouse', 'speaker', 'tower', 'laptop', 'part'],
  },

  { id: 'F.digital.represent', yearLevel: 'F', strand: 'data', title: 'Representing data with pictures',
    term: 2, content: 'Use pictures and symbols to represent and organise information.',
    activities: ['digital_activity'], variant: 'data_collection' as DigitalVariant,
    instructions: [
      'Choose a question to ask your friends',
      'Give everyone a picture card for their answer',
      'Sort the cards into groups',
      'Count how many in each group',
      'Draw a picture to show the groups',
      'Which group has the most?',
      'Which group has the fewest?',
    ],
    vocabulary: ['data', 'picture', 'symbol', 'group', 'sort', 'count', 'represent', 'information'],
  },

  { id: 'F.digital.sequences', yearLevel: 'F', strand: 'algorithms', title: 'Following instructions',
    term: 2, content: 'Follow and give precise step-by-step instructions.',
    activities: ['digital_activity'], variant: 'algorithm_builder' as DigitalVariant,
    instructions: [
      'Stand up from your chair',
      'Push your chair in',
      'Walk to the door',
      'Touch the door handle',
      'Walk back to your chair',
      'Pull your chair out',
      'Sit down',
    ],
    vocabulary: ['instruction', 'step', 'order', 'first', 'next', 'last', 'follow', 'sequence'],
  },

  { id: 'F.digital.order', yearLevel: 'F', strand: 'algorithms', title: 'Ordering steps',
    term: 3, content: 'Put everyday activities into the correct order.',
    activities: ['digital_activity'], variant: 'algorithm_builder' as DigitalVariant,
    instructions: [
      'Get two slices of bread',
      'Put one slice on the plate',
      'Spread butter on the bread',
      'Add the filling (cheese, Vegemite, etc.)',
      'Put the second slice on top',
      'Cut the sandwich in half',
      'Put the sandwich on a plate',
      'Clean up your workspace',
    ],
    vocabulary: ['algorithm', 'sequence', 'order', 'step-by-step', 'before', 'after', 'precise'],
  },

  { id: 'F.digital.safe', yearLevel: 'F', strand: 'digital_citizenship', title: 'Being safe online',
    term: 3, content: 'Learn basic rules for staying safe when using digital devices.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'Talk about what "online" means',
      'Discuss: who should you tell if something online upsets you?',
      'Learn the rule: never share your full name online',
      'Learn the rule: never share your address online',
      'Learn the rule: always ask a grown-up before going online',
      'Draw a poster about online safety',
      'Share your poster with the class',
    ],
    vocabulary: ['online', 'safe', 'private', 'password', 'trusted adult', 'personal information', 'internet'],
  },

  { id: 'F.digital.simple_patterns', yearLevel: 'F', strand: 'algorithms', title: 'Simple patterns',
    term: 4, content: 'Recognise, describe, and continue simple repeating patterns.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'Look at the pattern: red, blue, red, blue, red, ?',
      'What comes next?',
      'Try a harder pattern: star, star, moon, star, star, ?',
      'Create your own AB pattern with blocks',
      'Create an ABB pattern',
      'Create an ABC pattern',
      'Describe your pattern to a partner',
      'Can your partner continue it?',
    ],
    vocabulary: ['pattern', 'repeat', 'continue', 'predict', 'next', 'rule', 'AB', 'ABB', 'ABC'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // YEAR 1 (7 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: '1.digital.collect', yearLevel: '1', strand: 'data', title: 'Collecting data',
    term: 1, content: 'Collect and organise simple data using surveys and tallies.',
    activities: ['digital_activity'], variant: 'data_collection' as DigitalVariant,
    instructions: [
      'Choose a question to ask your classmates',
      'Create a simple survey with 3-4 options',
      'Ask 10 people your question',
      'Record each answer with a tally mark',
      'Count the tallies for each option',
      'Draw a picture graph of your results',
      'Write what you found out',
    ],
    vocabulary: ['data', 'survey', 'tally', 'graph', 'picture graph', 'results', 'count', 'compare'],
  },

  { id: '1.digital.represent_images', yearLevel: '1', strand: 'data', title: 'Representing with images',
    term: 1, content: 'Use images and icons to represent objects and ideas digitally.',
    activities: ['digital_activity'], variant: 'data_collection' as DigitalVariant,
    instructions: [
      'Look at these emojis — what do they represent?',
      'Can you draw a simple icon for "sunny"?',
      'Can you draw a simple icon for "rainy"?',
      'Use icons to make a weather chart',
      'What icon would you use for "happy"?',
      'Design three icons for your classroom rules',
      'Share your icons with a partner',
    ],
    vocabulary: ['icon', 'image', 'represent', 'symbol', 'design', 'communicate', 'digital', 'chart'],
  },

  { id: '1.digital.precise', yearLevel: '1', strand: 'algorithms', title: 'Precise instructions',
    term: 2, content: 'Write and follow precise step-by-step instructions for everyday tasks.',
    activities: ['digital_activity'], variant: 'algorithm_builder' as DigitalVariant,
    instructions: [
      'Write instructions for making your bed',
      'Give your instructions to a partner',
      'They must follow them EXACTLY as written',
      'Did they do it correctly?',
      'If not, which instruction was unclear?',
      'Rewrite the unclear instruction to be more precise',
      'Test again — did it work this time?',
    ],
    vocabulary: ['algorithm', 'precise', 'instruction', 'step', 'order', 'test', 'improve', 'specific'],
  },

  { id: '1.digital.debug', yearLevel: '1', strand: 'algorithms', title: 'Finding and fixing errors',
    term: 2, content: 'Identify errors in sequences and fix them (debugging).',
    activities: ['digital_activity'], variant: 'algorithm_builder' as DigitalVariant,
    instructions: [
      'Read this algorithm for brushing teeth',
      'Step 1: Put toothpaste on the brush',
      'Step 2: Put the brush in your mouth',
      'Step 3: Rinse your mouth — WAIT! Is something missing?',
      'Find the bug: we forgot to actually BRUSH!',
      'Fix the algorithm by adding the missing step',
      'Test your fixed algorithm',
      'Check: does it work now?',
    ],
    vocabulary: ['debug', 'bug', 'error', 'fix', 'test', 'algorithm', 'missing step', 'incorrect order'],
  },

  { id: '1.digital.branching', yearLevel: '1', strand: 'algorithms', title: 'Algorithms with decisions',
    term: 3, content: 'Create algorithms that include simple yes/no decisions.',
    activities: ['digital_activity'], variant: 'algorithm_builder' as DigitalVariant,
    instructions: [
      'Look outside the window',
      'Is it raining? If YES, go to step 3. If NO, go to step 5',
      'Get your raincoat',
      'Get your umbrella. Go to step 6',
      'Get your hat',
      'Get your water bottle',
      'Go outside',
    ],
    vocabulary: ['algorithm', 'decision', 'if', 'then', 'else', 'condition', 'branch', 'choice'],
  },

  { id: '1.digital.privacy', yearLevel: '1', strand: 'digital_citizenship', title: 'Being kind online',
    term: 3, content: 'Understand the importance of being kind and respectful in digital spaces.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'Discuss: what does it mean to be kind online?',
      'Read a scenario: someone said something mean in a game',
      'How would that make you feel?',
      'What could you do? (tell a trusted adult, walk away, be kind back)',
      'Write three rules for being kind online',
      'Create a "Digital Kindness" pledge',
      'Sign your pledge',
    ],
    vocabulary: ['kind', 'respectful', 'cyberbullying', 'empathy', 'trusted adult', 'digital citizen', 'responsible'],
  },

  { id: '1.digital.input_output', yearLevel: '1', strand: 'digital_systems', title: 'Input and output',
    term: 4, content: 'Identify input and output devices and how computers process information.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'What is input? (information going IN to a device)',
      'What is output? (information coming OUT of a device)',
      'Find examples of input: keyboard, mouse, microphone, camera',
      'Find examples of output: screen, speakers, printer',
      'Draw a device and label its inputs and outputs',
      'What happens inside the device?',
      'Draw the process: Input → Processing → Output',
    ],
    vocabulary: ['input', 'output', 'process', 'keyboard', 'screen', 'mouse', 'speaker', 'microphone'],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // YEAR 2 (8 nodes)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: '2.digital.tables', yearLevel: '2', strand: 'data', title: 'Organising data in tables',
    term: 1, content: 'Collect, organise, and display data using tables and simple graphs.',
    activities: ['digital_activity'], variant: 'data_collection' as DigitalVariant,
    instructions: [
      'Collect data about favourite sports in your class',
      'Create a table with two columns: Sport and Count',
      'Fill in the data from your survey',
      'Which sport is most popular?',
      'Which is least popular?',
      'Create a bar graph from your table',
      'Write three things you learned from the data',
    ],
    vocabulary: ['table', 'row', 'column', 'data', 'organise', 'bar graph', 'most', 'least', 'survey', 'category'],
  },

  { id: '2.digital.binary_intro', yearLevel: '2', strand: 'data', title: 'Introduction to binary',
    term: 1, content: 'Explore how computers use on/off (binary) to store information.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'Computers only understand two things: ON and OFF',
      'We write ON as 1 and OFF as 0',
      'Use cards with dots: 8, 4, 2, 1',
      'Turn cards face up or face down to make numbers',
      'How do you make the number 5? (4+1)',
      'How do you make the number 7? (4+2+1)',
      'What is the biggest number you can make? (15)',
      'Try making all numbers from 0 to 15',
    ],
    vocabulary: ['binary', 'on', 'off', 'bit', 'data', 'represent', 'number', 'code', 'digit', 'computer'],
  },

  { id: '2.digital.loops', yearLevel: '2', strand: 'algorithms', title: 'Loops and repetition',
    term: 2, content: 'Use loops to repeat steps in an algorithm efficiently.',
    activities: ['digital_activity'], variant: 'algorithm_builder' as DigitalVariant,
    instructions: [
      'Clap your hands twice',
      'Stomp your feet once',
      'Repeat steps 1-2 three more times',
      'Now write: "Repeat 4 times: clap clap, stomp"',
      'Which is shorter?',
      'Create your own pattern using a loop',
      'Write it with and without the repeat command',
      'Teach it to a partner',
    ],
    vocabulary: ['loop', 'repeat', 'pattern', 'cycle', 'times', 'sequence', 'iterate', 'efficient'],
  },

  { id: '2.digital.selection', yearLevel: '2', strand: 'algorithms', title: 'Selection and branching',
    term: 2, content: 'Create algorithms that make decisions based on conditions.',
    activities: ['digital_activity'], variant: 'algorithm_builder' as DigitalVariant,
    instructions: [
      'IF the number is even, put it in the left box',
      'ELSE put it in the right box',
      'Try with these numbers: 2, 5, 8, 3, 10, 7',
      'Now create your own IF/ELSE rule',
      'IF the word starts with a vowel, colour it red',
      'ELSE colour it blue',
      'Test with 10 words',
      'Check your partner\'s work',
    ],
    vocabulary: ['selection', 'if', 'else', 'condition', 'branch', 'decision', 'true', 'false', 'rule'],
  },

  { id: '2.digital.visual_code', yearLevel: '2', strand: 'algorithms', title: 'Visual programming',
    term: 3, content: 'Use visual programming blocks to create simple programs.',
    activities: ['digital_activity'], variant: 'visual_code' as DigitalVariant,
    instructions: [
      'Learn about visual programming blocks',
      'A MOVE block: moves forward one step',
      'A TURN block: turns left or right',
      'A REPEAT block: does something multiple times',
      'Use blocks to navigate a maze on paper',
      'Write the sequence of blocks needed',
      'Test by following your instructions with your finger',
      'Debug if you hit a wall!',
    ],
    vocabulary: ['program', 'code', 'block', 'move', 'turn', 'repeat', 'sequence', 'maze', 'debug', 'visual'],
  },

  { id: '2.digital.footprint', yearLevel: '2', strand: 'digital_citizenship', title: 'Digital footprint',
    term: 3, content: 'Understand that online actions leave traces (digital footprint).',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'What is a footprint? (a mark left behind)',
      'A digital footprint is a mark you leave online',
      'Every website you visit leaves a trace',
      'Every message you send leaves a trace',
      'Why should we be careful about our digital footprint?',
      'What would you want people to see about you online?',
      'Create a poster: "Think Before You Click"',
    ],
    vocabulary: ['digital footprint', 'trace', 'online', 'privacy', 'permanent', 'careful', 'reputation', 'think'],
  },

  { id: '2.digital.balance', yearLevel: '2', strand: 'digital_citizenship', title: 'Screen time balance',
    term: 4, content: 'Understand the importance of balancing screen time with other activities.',
    activities: ['digital_activity'], variant: 'pattern_finder' as DigitalVariant,
    instructions: [
      'How much time do you spend on screens each day?',
      'What else do you do in a day? (play, read, sleep, eat)',
      'Draw a pie chart of your typical day',
      'Is your screen time balanced?',
      'What happens if you have too much screen time?',
      'Create a plan for a balanced day',
      'Include outdoor play, reading, and family time',
    ],
    vocabulary: ['screen time', 'balance', 'healthy', 'activity', 'outdoor', 'limit', 'wellbeing', 'choice'],
  },

  { id: '2.digital.networks', yearLevel: '2', strand: 'digital_systems', title: 'Computer networks',
    term: 4, content: 'Understand how computers connect and share information over networks.',
    activities: ['digital_activity'], variant: 'grid_navigation' as DigitalVariant,
    instructions: [
      'A network connects computers together',
      'The internet is a very large network',
      'How does a message travel from one computer to another?',
      'Play the "message passing" game with string and cups',
      'What happens if the string breaks?',
      'How is WiFi different from a cable?',
      'Draw a simple network of computers',
      'Label the connections between them',
    ],
    vocabulary: ['network', 'internet', 'connect', 'WiFi', 'cable', 'server', 'message', 'share', 'link'],
  },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getDigitalForYear(yearLevel: 'F' | '1' | '2'): DigitalUnit[] {
  const prefix = yearLevel === 'F' ? 'F.' : `${yearLevel}.`;
  return DIGITAL_SEQUENCE.filter((u) => u.id.startsWith(prefix));
}
